/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ArSessionCodeRouteImport } from './routes/ar.$sessionCode'
import { Route as BatBatIdRouteImport } from './routes/bat.$batId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ArSessionCodeRoute = ArSessionCodeRouteImport.update({
  id: '/ar/$sessionCode',
  path: '/ar/$sessionCode',
  getParentRoute: () => rootRouteImport,
} as any)
const BatBatIdRoute = BatBatIdRouteImport.update({
  id: '/bat/$batId',
  path: '/bat/$batId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/$sessionCode': typeof ArSessionCodeRoute
  '/bat/$batId': typeof BatBatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/$sessionCode': typeof ArSessionCodeRoute
  '/bat/$batId': typeof BatBatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/$sessionCode': typeof ArSessionCodeRoute
  '/bat/$batId': typeof BatBatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/ar/$sessionCode' | '/bat/$batId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/ar/$sessionCode' | '/bat/$batId'
  id: '__root__' | '/' | '/sitemap.xml' | '/ar/$sessionCode' | '/bat/$batId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArSessionCodeRoute: typeof ArSessionCodeRoute
  BatBatIdRoute: typeof BatBatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/$sessionCode': {
      id: '/ar/$sessionCode'
      path: '/ar/$sessionCode'
      fullPath: '/ar/$sessionCode'
      preLoaderRoute: typeof ArSessionCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bat/$batId': {
      id: '/bat/$batId'
      path: '/bat/$batId'
      fullPath: '/bat/$batId'
      preLoaderRoute: typeof BatBatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArSessionCodeRoute: ArSessionCodeRoute,
  BatBatIdRoute: BatBatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
